config/routes.rb
Rails.application.routes.draw do
  get 'tweets/index'
  resources :tweets

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new; end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.save
    redirect_to @tweet
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:username, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AliTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Tweets</h1>
<%= link_to 'New Tweet', new_tweet_path %>
<table>
  <tr>
    <th>Username</th>
    <th>Tweet</th>
  </tr>

  <% @tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.username %></td>
      <td><%= tweet.text %></td>
      <td><%= link_to 'Delete', tweet_path(tweet),
                      method: :delete,
                      data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/tweets/new.html.erb
<%= form_with scope: :tweet, url: tweets_path, local: true do |form| %>
  <p>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>username:</strong>
  <%= @tweet.username %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<%= link_to 'Back', tweets_path %>